### ISSUE TITLE
ValueError: Shape mismatch for blis.gemm: (0, 0), (576, 288)

### ISSUE THREAD

**Issue by seanxiaoyan** [h4iku/bug-localization#4]
Hi, I got this error when doing the aspectj dataset

```
Parsing & Preprocessing...
Token Matching...
VSM Similarity...
Stack Trace...
Semantic Similarity...
Traceback (most recent call last):
  File "buglocalizer/main.py", line 22, in <module>
    semantic_similarity.main()
  File "/home/xu/bug-localization/buglocalizer/semantic_similarity.py", line 50, in main
    all_simis = calculate_similarity(src_files, bug_reports)
  File "/home/xu/bug-localization/buglocalizer/semantic_similarity.py", line 16, in calculate_similarity
    src_docs = [nlp(' '.join(src.file_name['unstemmed'] + src.class_names['unstemmed']
  File "/home/xu/bug-localization/buglocalizer/semantic_similarity.py", line 16, in <listcomp>
    src_docs = [nlp(' '.join(src.file_name['unstemmed'] + src.class_names['unstemmed']
  File "/home/x/.local/lib/python3.8/site-packages/spacy/language.py", line 1019, in __call__
    error_handler(name, proc, [doc], e)
  File "/home/xu/.local/lib/python3.8/site-packages/spacy/util.py", line 1618, in raise_error
    raise e
  File "/home/xu/.local/lib/python3.8/site-packages/spacy/language.py", line 1014, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "spacy/pipeline/trainable_pipe.pyx", line 56, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__
  File "/home/xu/.local/lib/python3.8/site-packages/spacy/util.py", line 1618, in raise_error
    raise e
  File "spacy/pipeline/trainable_pipe.pyx", line 52, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__
  File "/home/xu/.local/lib/python3.8/site-packages/spacy/pipeline/tok2vec.py", line 121, in predict
    tokvecs = self.model.predict(docs)
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/model.py", line 315, in predict
    return self._func(self, X, is_train=False)[0]
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/layers/chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/layers/chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/layers/with_array.py", line 30, in forward
    return _ragged_forward(
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/layers/with_array.py", line 90, in _ragged_forward
    Y, get_dX = layer(Xr.dataXd, is_train)
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/layers/chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/layers/chain.py", line 54, in forward
    Y, inc_layer_grad = layer(X, is_train=is_train)
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/model.py", line 291, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/xu/.local/lib/python3.8/site-packages/thinc/layers/maxout.py", line 49, in forward
    Y = model.ops.gemm(X, W, trans2=True)
  File "thinc/backends/numpy_ops.pyx", line 93, in thinc.backends.numpy_ops.NumpyOps.gemm
  File "blis/py.pyx", line 74, in blis.py.gemm
ValueError: Shape mismatch for blis.gemm: (0, 0), (576, 288)
```

**Comment by h4iku** [comment]
Hi
This seems to be a bug in older versions of SpaCy: https://github.com/explosion/spaCy/issues/10334
Upgrading to `spacy==3.2.4` fixes the issue. I'll update the requirements as well.
Thank you

**Comment by seanxiaoyan** [comment]
Thank you
